# Generated by Django 3.0.5 on 2020-05-13 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mouth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('t_11', models.CharField(default='sano', max_length=90)),
                ('t_12', models.CharField(default='sano', max_length=90)),
                ('t_13', models.CharField(default='sano', max_length=90)),
                ('t_14', models.CharField(default='sano', max_length=90)),
                ('t_15', models.CharField(default='sano', max_length=90)),
                ('t_16', models.CharField(default='sano', max_length=90)),
                ('t_17', models.CharField(default='sano', max_length=90)),
                ('t_18', models.CharField(default='sano', max_length=90)),
                ('t_21', models.CharField(default='sano', max_length=90)),
                ('t_22', models.CharField(default='sano', max_length=90)),
                ('t_23', models.CharField(default='sano', max_length=90)),
                ('t_24', models.CharField(default='sano', max_length=90)),
                ('t_25', models.CharField(default='sano', max_length=90)),
                ('t_26', models.CharField(default='sano', max_length=90)),
                ('t_27', models.CharField(default='sano', max_length=90)),
                ('t_28', models.CharField(default='sano', max_length=90)),
                ('t_31', models.CharField(default='sano', max_length=90)),
                ('t_32', models.CharField(default='sano', max_length=90)),
                ('t_33', models.CharField(default='sano', max_length=90)),
                ('t_34', models.CharField(default='sano', max_length=90)),
                ('t_35', models.CharField(default='sano', max_length=90)),
                ('t_36', models.CharField(default='sano', max_length=90)),
                ('t_37', models.CharField(default='sano', max_length=90)),
                ('t_38', models.CharField(default='sano', max_length=90)),
                ('t_41', models.CharField(default='sano', max_length=90)),
                ('t_42', models.CharField(default='sano', max_length=90)),
                ('t_43', models.CharField(default='sano', max_length=90)),
                ('t_44', models.CharField(default='sano', max_length=90)),
                ('t_45', models.CharField(default='sano', max_length=90)),
                ('t_46', models.CharField(default='sano', max_length=90)),
                ('t_47', models.CharField(default='sano', max_length=90)),
                ('t_48', models.CharField(default='sano', max_length=90)),
                ('t_51', models.CharField(default='sano', max_length=90)),
                ('t_52', models.CharField(default='sano', max_length=90)),
                ('t_53', models.CharField(default='sano', max_length=90)),
                ('t_54', models.CharField(default='sano', max_length=90)),
                ('t_55', models.CharField(default='sano', max_length=90)),
                ('t_61', models.CharField(default='sano', max_length=90)),
                ('t_62', models.CharField(default='sano', max_length=90)),
                ('t_63', models.CharField(default='sano', max_length=90)),
                ('t_64', models.CharField(default='sano', max_length=90)),
                ('t_65', models.CharField(default='sano', max_length=90)),
                ('t_71', models.CharField(default='sano', max_length=90)),
                ('t_72', models.CharField(default='sano', max_length=90)),
                ('t_73', models.CharField(default='sano', max_length=90)),
                ('t_74', models.CharField(default='sano', max_length=90)),
                ('t_75', models.CharField(default='sano', max_length=90)),
                ('t_81', models.CharField(default='sano', max_length=90)),
                ('t_82', models.CharField(default='sano', max_length=90)),
                ('t_83', models.CharField(default='sano', max_length=90)),
                ('t_84', models.CharField(default='sano', max_length=90)),
                ('t_85', models.CharField(default='sano', max_length=90)),
            ],
        ),
    ]
