# Generated by Django 3.0.5 on 2020-05-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mouth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_11', models.CharField(choices=[('C_11_01', 'C_11_01'), ('C_11_02', 'C_11_02'), ('C_11_03', 'C_11_03'), ('C_11_04', 'C_11_04'), ('C_11_05', 'C_11_05')], max_length=400)),
            ],
        ),
    ]
