# Generated by Django 3.0.5 on 2020-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouth',
            name='t_12',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_13',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_14',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_15',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_16',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_17',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_18',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(default='', max_length=400),
        ),
    ]
