# Generated by Django 3.0.5 on 2020-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200503_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_12',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_13',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_14',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_15',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_16',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_17',
            field=models.CharField(default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_18',
            field=models.CharField(default='zero', max_length=400),
        ),
    ]
