# Generated by Django 3.0.5 on 2020-05-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200503_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_12',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_13',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_14',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_15',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_16',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_17',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_18',
            field=models.CharField(choices=[('zero', 'zero'), ('C_01', 'C_01'), ('C_02', 'C_02'), ('C_03', 'C_03'), ('C_04', 'C_04'), ('C_05', 'C_05'), ('R_01', 'R_01'), ('R_02', 'R_02'), ('R_03', 'R_03'), ('R_04', 'R_04'), ('R_05', 'R_05'), ('E', 'E'), ('P', 'P'), ('Z', 'Z'), ('A', 'A'), ('D', 'D')], default='zero', max_length=400),
        ),
    ]
