# Generated by Django 3.0.5 on 2020-05-10 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200504_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_12',
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_13',
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_14',
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_15',
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_16',
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_17',
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_18',
        ),
        migrations.AddField(
            model_name='mouth',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.RemoveField(
            model_name='mouth',
            name='t_11',
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_11',
            field=models.ManyToManyField(blank=True, related_name='t_11', to='records.Proceeding'),
        ),
    ]
