# Generated by Django 3.0.5 on 2020-05-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200510_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceeding',
            name='code',
        ),
        migrations.AlterField(
            model_name='proceeding',
            name='name',
            field=models.CharField(choices=[('good', 'sano'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('c5', 'c%')], default='good', max_length=50),
        ),
    ]
