# Generated by Django 3.0.5 on 2020-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20200510_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(choices=[('1', 'sano'), ('2', 'c1'), ('3', 'c2'), ('4', 'c3'), ('5', 'c4'), ('6', 'c5')], default='good', max_length=50),
        ),
    ]
