# Generated by Django 3.0.5 on 2020-05-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20200510_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(choices=[('sano', 'sano'), ('c1', 'c1'), ('c2', 'c2'), ('c3', 'c3'), ('c4', 'c4'), ('c5', 'c5')], default='good', max_length=50),
        ),
    ]
