# Generated by Django 3.0.5 on 2020-05-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20200510_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(default='good', max_length=70),
        ),
    ]
