# Generated by Django 3.0.5 on 2020-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20200510_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouth',
            name='t_12',
            field=models.CharField(default='sano', max_length=70),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_13',
            field=models.CharField(default='sano', max_length=70),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(default='sano', max_length=70),
        ),
    ]
