# Generated by Django 3.0.5 on 2020-05-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20200511_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouth',
            name='t_14',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_15',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_16',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_17',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_18',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_21',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_22',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_23',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_24',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_25',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_26',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_27',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_28',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_31',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_32',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_33',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_34',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_35',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_36',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_37',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_38',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_41',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_42',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_43',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_44',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_45',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_46',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_47',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_48',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_51',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_52',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_53',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_54',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_55',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_61',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_62',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_63',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_64',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_65',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_71',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_72',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_73',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_74',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_75',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_81',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_82',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_83',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_84',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AddField(
            model_name='mouth',
            name='t_85',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_11',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_12',
            field=models.CharField(default='sano', max_length=90),
        ),
        migrations.AlterField(
            model_name='mouth',
            name='t_13',
            field=models.CharField(default='sano', max_length=90),
        ),
    ]
